language: node_js
node_js:
- node
addons:
  sonarcloud:
    organization: timoa-github
script:
- npm run test:coverage
- bash scripts/sonar_scanner.sh
notifications:
  email:
    on_success: never
    on_failure: always