name: Code Analysis

on: [push]

jobs:
  sonarCloudTrigger:

    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: SonarCloud Scan
      uses: timoa/cdkit.appstore.design@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}